const Koa = require("koa");
const BodyParser = require("koa-bodyparser");
const logger = require("koa-logger");
const static = require("koa-static");
const app = new Koa();
require("dotenv").config();
app.use(BodyParser());
app.use(logger());
app.use(static(__dirname + "/public", {}));
require("./app/routes")(app);
console.log(`App listenng @ http://127.0.0.1:${process.env.PORT || 3000}`);
app.listen(process.env.PORT || 3000);
